flowchart TB
    dorm["<b>Dorm</b>"] --> bar["<b>Bar</b>"] & coppersmith_carriage["<b>Coppersmith Carriage</b>"] & mess_hall["<b>Mess Hall</b>"]
    furnace["<b>Furnace</b>"] --> mind["<b>Mind</b>"]
    bar --> gambling["<b>Gambling</b>"]
    frayed_end["<b>Frayed End</b>"] --> currency["<b>Currency</b>"]
    coppersmith_carriage --> crankshafts@{ label: "<b>Crankshaft's</b>" } & bank["<b>Bank</b>"] & frayed_end
    frayed_end --> secret_passage["<b>Secret Passage</b>"]
    pay["<b>Pay</b>"]