name: "Export Godot Game to HTML5"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GODOT_VERSION: 4.5

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Export to Web
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_export_templates.tpk
          relative_project_path: ./
          archive_output: false
          export_debug: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.export.outputs.build_directory }}
          force_orphan: true
